export const test: Game[] = [
  {
    id: 540,
    title: 'Overwatch 2',
    thumbnail: 'https://www.freetogame.com/g/540/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'Activision Blizzard',
    release_date: '2022-10-04',
  },
  {
    id: 521,
    title: 'Diablo Immortal',
    thumbnail: 'https://www.freetogame.com/g/521/thumbnail.jpg',
    genre: 'MMOARPG',
    developer: 'Blizzard Entertainment',
    release_date: '2022-06-02',
  },
  {
    id: 517,
    title: 'Lost Ark',
    thumbnail: 'https://www.freetogame.com/g/517/thumbnail.jpg',
    genre: 'ARPG',
    developer: 'Amazon Games',
    release_date: '2022-02-11',
  },
  {
    id: 516,
    title: 'PUBG: BATTLEGROUNDS',
    thumbnail: 'https://www.freetogame.com/g/516/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'KRAFTON, Inc.',
    release_date: '2022-01-12',
  },
  {
    id: 508,
    title: 'Enlisted',
    thumbnail: 'https://www.freetogame.com/g/508/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'Gaijin Entertainment',
    release_date: '2021-04-08',
  },
  {
    id: 345,
    title: 'Forge of Empires',
    thumbnail: 'https://www.freetogame.com/g/345/thumbnail.jpg',
    genre: 'Strategy',
    developer: 'InnoGames',
    release_date: '2012-04-17',
  },
  {
    id: 427,
    title: 'Drakensang Online',
    thumbnail: 'https://www.freetogame.com/g/427/thumbnail.jpg',
    genre: 'MMORPG',
    developer: 'Bigpoint',
    release_date: '2011-08-08',
  },
  {
    id: 525,
    title: 'MultiVersus',
    thumbnail: 'https://www.freetogame.com/g/525/thumbnail.jpg',
    genre: 'Fighting',
    developer: 'Player First Games',
    release_date: '2022-07-19',
  },
  {
    id: 475,
    title: 'Genshin Impact',
    thumbnail: 'https://www.freetogame.com/g/475/thumbnail.jpg',
    genre: 'Action RPG',
    developer: 'miHoYo',
    release_date: '2020-09-28',
  },
  {
    id: 523,
    title: 'Fall Guys',
    thumbnail: 'https://www.freetogame.com/g/523/thumbnail.jpg',
    genre: 'Battle Royale',
    developer: 'Mediatonic',
    release_date: '2020-08-04',
  },
  {
    id: 340,
    title: 'Game Of Thrones Winter Is Coming',
    thumbnail: 'https://www.freetogame.com/g/340/thumbnail.jpg',
    genre: 'Strategy',
    developer: 'YOOZOO Games ',
    release_date: '2019-11-14',
  },
  {
    id: 347,
    title: 'Elvenar',
    thumbnail: 'https://www.freetogame.com/g/347/thumbnail.jpg',
    genre: 'Strategy',
    developer: 'InnoGames',
    release_date: '2015-04-08',
  },
  {
    id: 11,
    title: 'Neverwinter',
    thumbnail: 'https://www.freetogame.com/g/11/thumbnail.jpg',
    genre: 'MMORPG',
    developer: 'Cryptic Studios',
    release_date: '2013-12-06',
  },
  {
    id: 380,
    title: 'Dark Orbit Reloaded',
    thumbnail: 'https://www.freetogame.com/g/380/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'Bigpoint',
    release_date: '2006-12-11',
  },
  {
    id: 515,
    title: 'Halo Infinite',
    thumbnail: 'https://www.freetogame.com/g/515/thumbnail.jpg',
    genre: 'Shooter',
    developer: '343 Industries',
    release_date: '2021-11-15',
  },
  {
    id: 455,
    title: 'Eternal Fury',
    thumbnail: 'https://www.freetogame.com/g/455/thumbnail.jpg',
    genre: 'MMORPG',
    developer: 'R2 Games',
    release_date: '2019-05-21',
  },
  {
    id: 522,
    title: 'Flyff Universe',
    thumbnail: 'https://www.freetogame.com/g/522/thumbnail.jpg',
    genre: 'MMORPG',
    developer: 'Gala Lab',
    release_date: '2022-06-14',
  },
  {
    id: 511,
    title: 'Phantasy Star Online 2 New Genesis',
    thumbnail: 'https://www.freetogame.com/g/511/thumbnail.jpg',
    genre: 'MMORPG',
    developer: 'Sega',
    release_date: '2021-06-09',
  },
  {
    id: 5,
    title: 'Crossout',
    thumbnail: 'https://www.freetogame.com/g/5/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'Gaijin',
    release_date: '2017-05-30',
  },
  {
    id: 9,
    title: 'World of Warships',
    thumbnail: 'https://www.freetogame.com/g/9/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'Wargaming',
    release_date: '2015-07-02',
  },
  {
    id: 12,
    title: 'War Thunder',
    thumbnail: 'https://www.freetogame.com/g/12/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'Gaijin Entertainment',
    release_date: '2013-08-15',
  },
  {
    id: 2,
    title: 'World of Tanks',
    thumbnail: 'https://www.freetogame.com/g/2/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'Wargaming',
    release_date: '2011-04-12',
  },
  {
    id: 458,
    title: "League of Angels - Heaven's Fury",
    thumbnail: 'https://www.freetogame.com/g/458/thumbnail.jpg',
    genre: 'MMORPG',
    developer: 'Yoozoo Games',
    release_date: '2020-01-09',
  },
  {
    id: 529,
    title: 'Tower of Fantasy',
    thumbnail: 'https://www.freetogame.com/g/529/thumbnail.jpg',
    genre: 'MMORPG',
    developer: 'Hotta Studio',
    release_date: '2022-08-10',
  },
  {
    id: 528,
    title: 'Noah’s Heart',
    thumbnail: 'https://www.freetogame.com/g/528/thumbnail.jpg',
    genre: 'MMORPG',
    developer: 'Archosaur Games',
    release_date: '2022-07-28',
  },
  {
    id: 466,
    title: 'Valorant',
    thumbnail: 'https://www.freetogame.com/g/466/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'Riot Games',
    release_date: '2020-06-02',
  },
  {
    id: 467,
    title: 'Phantasy Star Online 2',
    thumbnail: 'https://www.freetogame.com/g/467/thumbnail.jpg',
    genre: 'MMORPG',
    developer: 'SEGA',
    release_date: '2020-05-27',
  },
  {
    id: 452,
    title: 'Call Of Duty: Warzone',
    thumbnail: 'https://www.freetogame.com/g/452/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'Infinity Ward',
    release_date: '2020-03-10',
  },
  {
    id: 21,
    title: 'Destiny 2',
    thumbnail: 'https://www.freetogame.com/g/21/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'Bungie',
    release_date: '2019-10-01',
  },
  {
    id: 1,
    title: 'Dauntless',
    thumbnail: 'https://www.freetogame.com/g/1/thumbnail.jpg',
    genre: 'MMORPG',
    developer: 'Phoenix Labs, Iron Galaxy',
    release_date: '2019-05-21',
  },
  {
    id: 23,
    title: 'Apex Legends',
    thumbnail: 'https://www.freetogame.com/g/23/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'Electronic Arts',
    release_date: '2019-02-04',
  },
  {
    id: 57,
    title: 'Fortnite',
    thumbnail: 'https://www.freetogame.com/g/57/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'Epic Games',
    release_date: '2017-09-26',
  },
  {
    id: 449,
    title: 'Albion Online',
    thumbnail: 'https://www.freetogame.com/g/449/thumbnail.jpg',
    genre: 'MMORPG',
    developer: 'Sandbox Interactive GmbH',
    release_date: '2017-07-17',
  },
  {
    id: 6,
    title: 'Blade and Soul',
    thumbnail: 'https://www.freetogame.com/g/6/thumbnail.jpg',
    genre: 'MMORPG',
    developer: 'NCSoft',
    release_date: '2016-01-19',
  },
  {
    id: 212,
    title: 'Brawlhalla',
    thumbnail: 'https://www.freetogame.com/g/212/thumbnail.jpg',
    genre: 'Fighting',
    developer: 'Blue Mammoth Games',
    release_date: '2015-11-03',
  },
  {
    id: 8,
    title: 'Trove',
    thumbnail: 'https://www.freetogame.com/g/8/thumbnail.jpg',
    genre: 'MMORPG',
    developer: 'Trion Worlds',
    release_date: '2015-07-09',
  },
  {
    id: 202,
    title: 'Heroes & Generals',
    thumbnail: 'https://www.freetogame.com/g/202/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'Reto-Moto',
    release_date: '2014-07-11',
  },
  {
    id: 207,
    title: 'Warface',
    thumbnail: 'https://www.freetogame.com/g/207/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'Crytek',
    release_date: '2014-07-01',
  },
  {
    id: 217,
    title: 'Smite',
    thumbnail: 'https://www.freetogame.com/g/217/thumbnail.jpg',
    genre: 'MOBA',
    developer: 'Hi-Rez Studios',
    release_date: '2014-03-25',
  },
  {
    id: 3,
    title: 'Warframe',
    thumbnail: 'https://www.freetogame.com/g/3/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'Digital Extremes',
    release_date: '2013-03-25',
  },
  {
    id: 243,
    title: 'PlanetSide 2',
    thumbnail: 'https://www.freetogame.com/g/243/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'Daybreak Games',
    release_date: '2012-11-21',
  },
  {
    id: 13,
    title: 'Guild Wars 2',
    thumbnail: 'https://www.freetogame.com/g/13/thumbnail.jpg',
    genre: 'MMORPG',
    developer: 'ArenaNet',
    release_date: '2012-08-28',
  },
  {
    id: 350,
    title: 'Goodgame Empire',
    thumbnail: 'https://www.freetogame.com/g/350/thumbnail.jpg',
    genre: 'Strategy',
    developer: 'Goodgame Studios',
    release_date: '2011-08-14',
  },
  {
    id: 14,
    title: 'Star Trek Online',
    thumbnail: 'https://www.freetogame.com/g/14/thumbnail.jpg',
    genre: 'MMORPG',
    developer: ' Cryptic Studios',
    release_date: '2010-02-02',
  },
  {
    id: 433,
    title: 'RuneScape',
    thumbnail: 'https://www.freetogame.com/g/433/thumbnail.jpg',
    genre: 'MMORPG',
    developer: 'Jagex',
    release_date: '2001-01-04',
  },
  {
    id: 558,
    title: 'Hawked',
    thumbnail: 'https://www.freetogame.com/g/558/thumbnail.jpg',
    genre: 'Shooter',
    developer: 'My.Games',
    release_date: '2023-08-03',
  },
  {
    id: 559,
    title: 'Tales Of Yore',
    thumbnail: 'https://www.freetogame.com/g/559/thumbnail.jpg',
    genre: 'MMORPG',
    developer: 'Coke And Code',
    release_date: '2023-08-08',
  },
  {
    id: 560,
    title: 'Palia',
    thumbnail: 'https://www.freetogame.com/g/560/thumbnail.jpg',
    genre: 'MMORPG',
    developer: 'Singularity Six',
    release_date: '2023-08-10',
  },
];
